### PR TITLE
Ev acilab

### PR DESCRIPTION
**Pull request by evillgenius75**
Added Virtual-Kubelet and ACI lab to day 2. Based on Demo I showed during Azure Container team Show and Tell Friday March 9th. Uses Current Heroes Project as a 2 container Pod being deployed to ACI via Virtual Kubelet on AKS. Also uses new dns label mechanism to create a Traffic Manager profile to make a Global Load Balanced ACI Service.

### CODE REVIEW

**Comment by chzbrgr71** [comment]
This is a good PR. We need to get this merged in and added to the day 2 labs. One QQ. In the step where they `Create a service principal`, can we just have them use the one provided by Spektra? Or at least note that they don't need to create it if they are in the classroom setup. 

I plan to test this out today/tomorrow using a Spektra setup just to be sure.

**Comment by chzbrgr71** [comment]
In the helm install command, it still says `env.nodeOsType=<Linux|Windows>` which caused an error. Switched it to Linux and the command worked.

**Comment by evillgenius75** [comment]
chzbrgr71 that is a good question. For my tests I pulled from my Docker hub account so didn't need a pull secret. I will need to ask the virt-kube folks how that works? Does ACI use the ImagePullSecret creds or is there something else in the pod spec that has to be used to pull from a private registry.

**Comment by evillgenius75** [comment]
I just asked Ria and it seems that ImagePullSecrets is respected by ACI so i will add the ImagePullSecrets to the PodSpec since the students should already have that in their cluster.

**Pull request merged**
