### PR TITLE
Create PVC walkthrough for azure files

### PR DESCRIPTION
**Pull request by lastcoolnameleft**

### CODE REVIEW

**Comment by spacecat** [comment]
Any ETA when this PR will be merged into master?

**Comment by lastcoolnameleft** [comment]
The last time we spoke about it, I believe the blackbelt team wanted everything to integrate with the existing walkthrough of a MongoDB app to K8S; however, this PR is a standalone example so, it doesn't fit the theme.

@evillgenius75  @chzbrgr71  should I close this PR?

**Comment by chzbrgr71** [comment]
Probably makes sense to close these until we have something integrated into the sample app used in the labs. But I'd like input from the others on the team. @dstrebel @jschluchter @kevingbb @raykao @evillgenius75

**Comment by chzbrgr71** [comment]
I suggest that we close these for now. Happy to re-open later.

**Pull request closed without merging**
